# Generated by Django 3.0.6 on 2021-07-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewerip',
            name='location',
            field=models.CharField(db_column='FstrLocation', default='', max_length=256),
        ),
    ]
