# Generated by Django 3.1.7 on 2021-03-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockConfig',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='序号')),
                ('business_name', models.CharField(max_length=50, verbose_name='业务名称')),
                ('business_tip', models.CharField(max_length=50, verbose_name='业务标识')),
                ('message_format', models.SmallIntegerField(default=0, verbose_name='报文格式 1:json 2:xml 3:form')),
                ('mock_type', models.SmallIntegerField(default=0, verbose_name='Mock匹配方式 1:通用地址前缀+业务标识+接口标识 2:通用地址前缀+业务标识，接口标识从请求参数获取')),
                ('mock_match_field', models.CharField(default='', max_length=50, null=True, verbose_name='接口匹配字段')),
                ('is_diff_merchant', models.SmallIntegerField(default=0, verbose_name='是否区分商户号 0:否 1:是')),
                ('merchant_field', models.CharField(default='', max_length=50, null=True, verbose_name='商户号取值字段')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('description', models.TextField(default='', verbose_name='项目描述')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('description', models.TextField(default='', verbose_name='模块描述')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester_home.project')),
            ],
        ),
    ]
