# Generated by Django 3.1.6 on 2021-02-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='', verbose_name='模块描述'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.BooleanField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='module',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
