# Generated by Django 3.1.6 on 2021-02-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester_home', '0002_auto_20210226_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockConfig',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='序号')),
                ('business_name', models.CharField(max_length=50, verbose_name='业务名称')),
                ('business_tip', models.CharField(max_length=50, verbose_name='业务标识')),
                ('message_format', models.SmallIntegerField(default=0, verbose_name='报文格式 1:json 2:xml 3:form')),
                ('mock_type', models.SmallIntegerField(default=0, verbose_name='Mock匹配方式 1:通用地址前缀+业务标识+接口标识 2:通用地址前缀+业务标识，接口标识从请求参数获取')),
                ('mock_field', models.CharField(default='', max_length=50, null=True, verbose_name='接口匹配字段')),
                ('is_diff_merchant', models.SmallIntegerField(default=0, verbose_name='是否区分商户号 0:否 1:是')),
                ('merchant_field', models.CharField(default='', max_length=50, null=True, verbose_name='商户号取值字段')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
