# Generated by Django 3.1.6 on 2021-03-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester_home', '0002_auto_20210304_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockconfig',
            name='id',
            field=models.SmallIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
