# Generated by Django 3.1.6 on 2021-03-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester_home', '0003_auto_20210304_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
